### ISSUE TITLE
How to set for front page user?

### ISSUE THREAD

**Issue by hoangphuong** [jacobbuck/wp-tag-select-meta-box#1]
How to set for front page user?
thanks

**Comment by jacobbuck** [comment]
Hi there, I don't understand what you mean by setting for "front page user"?

Also this plugin is no longer supported as I haven't worked with WordPress in years.

**Comment by hoangphuong** [comment]
Hi, 
"front page user" -> "front-end page"
the post page for user, not admin
thanks

**Comment by jacobbuck** [comment]
Oh right, it was only built to work in the WordPress admin, so it currently can't be set up for anything else.
